### ISSUE TITLE
GetFeeds URL Empty?

### ISSUE THREAD

**Issue by vnmaster1997** [mdanics/fluttergram#105] opened 2020-10-05 03:56 UTC
After following the fluttergram's steps on github, logged in to the application but no news was displayed even though I followed other users and also made a few posts.
P/s: I checked firebase cloud storage, and got the data, but when using getFeed Url in my browser I didn't get any data.

my Link GetFeed URL: http://us-central1-flutterinstagram-4602d.cloudfunctions.net/getFeed?uid=108392313037367780811

![image](https://user-images.githubusercontent.com/39695071/95038822-4f2e7480-06f9-11eb-81b3-7650f1e45924.png)
And this is my data in clound function:
![image](https://user-images.githubusercontent.com/39695071/95038894-6bcaac80-06f9-11eb-8a2a-3fcf670c0c27.png)

Please help me !!

**Comment by tilakpatel22** [comment] 2020-10-06 06:08
i was facing the same problem and this is because u might not have enable the billing account in firebase so i was also confused and after that i figure out how can i build app without cloud functions. so first go to your feed.dart and paste this code.

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:foodizo/upload_page.dart';
import 'comment_screen.dart';


class Feed extends StatefulWidget {
  @override
  _FeedState createState() => _FeedState();
}

class _FeedState extends State<Feed> {
  CollectionReference postcol = Firestore.instance.collection('insta_posts');
  CollectionReference usercol = Firestore.instance.collection('insta_users');

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      floatingActionButton: FloatingActionButton(
        mini: true,
        onPressed: () => Navigator.push(
            context, MaterialPageRoute(builder: (context) => Uploader())),
        child: Icon(Icons.add, size: 32),
      ),
      body: StreamBuilder(
          stream: postcol.snapshots(),
          // ignore: missing_return
          builder: (context, snapshot) {
            return ListView.builder(
                itemCount: snapshot.data.documents.length,
                itemBuilder: (BuildContext context, int index) {
                  DocumentSnapshot same = snapshot.data.documents[index];
                  return Card(
                    child: ListTile(
                      leading: CircleAvatar(
                        backgroundColor: Colors.black,
                        backgroundImage: NetworkImage(''),
                      ),
                      title: Text(
                        same['username'],
                      ),
                      subtitle: Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          if (same['number'] == 1)
                            Column(
                              children: [
                                Text(
                                  same['description'],
                                ),
                                SizedBox(
                                  height: 10,
                                ),
                                Image(image: NetworkImage(same['mediaUrl'])),
                              ],
                            ),
                          SizedBox(height: 10),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.spaceBetween,
                            children: [
                              Row(
                                children: [
                                  InkWell(
                                    onTap: () => Navigator.push(
                                        context,
                                        MaterialPageRoute(
                                            builder: (context) =>
                                                CommentScreen())),
                                    child: Icon(Icons.comment),
                                  ),
                                  SizedBox(
                                    width: 10.0,
                                  ),
                                  Text(
                                    same['commentcount'].toString(),
                                  ),
                                ],
                              ),
                            ],
                          )
                        ],
                      ),
                    ),
                  );
                });
          }),
    );
  }
}

you need to figure out some things by yourself like comments and likes after applying this code feeds will be visible at your home page.

AND THAT'S IT HOPE THIS WORK FOR YOU !!

**Comment by vnmaster1997** [comment] 2020-10-13 07:03
thansk

> i was facing the same problem and this is because u might not have enable the billing account in firebase so i was also confused and after that i figure out how can i build app without cloud functions. so first go to your feed.dart and paste this code.
> 
> import 'package:cloud_firestore/cloud_firestore.dart';
> import 'package:flutter/material.dart';
> import 'package:foodizo/upload_page.dart';
> import 'comment_screen.dart';
> 
> class Feed extends StatefulWidget {
> @override
> _FeedState createState() => _FeedState();
> }
> 
> class _FeedState extends State {
> CollectionReference postcol = Firestore.instance.collection('insta_posts');
> CollectionReference usercol = Firestore.instance.collection('insta_users');
> 
> @override
> void initState() {
> super.initState();
> }
> 
> @override
> Widget build(BuildContext context) {
> return Scaffold(
> floatingActionButton: FloatingActionButton(
> mini: true,
> onPressed: () => Navigator.push(
> context, MaterialPageRoute(builder: (context) => Uploader())),
> child: Icon(Icons.add, size: 32),
> ),
> body: StreamBuilder(
> stream: postcol.snapshots(),
> // ignore: missing_return
> builder: (context, snapshot) {
> return ListView.builder(
> itemCount: snapshot.data.documents.length,
> itemBuilder: (BuildContext context, int index) {
> DocumentSnapshot same = snapshot.data.documents[index];
> return Card(
> child: ListTile(
> leading: CircleAvatar(
> backgroundColor: Colors.black,
> backgroundImage: NetworkImage(''),
> ),
> title: Text(
> same['username'],
> ),
> subtitle: Column(
> crossAxisAlignment: CrossAxisAlignment.start,
> children: [
> if (same['number'] == 1)
> Column(
> children: [
> Text(
> same['description'],
> ),
> SizedBox(
> height: 10,
> ),
> Image(image: NetworkImage(same['mediaUrl'])),
> ],
> ),
> SizedBox(height: 10),
> Row(
> mainAxisAlignment: MainAxisAlignment.spaceBetween,
> children: [
> Row(
> children: [
> InkWell(
> onTap: () => Navigator.push(
> context,
> MaterialPageRoute(
> builder: (context) =>
> CommentScreen())),
> child: Icon(Icons.comment),
> ),
> SizedBox(
> width: 10.0,
> ),
> Text(
> same['commentcount'].toString(),
> ),
> ],
> ),
> ],
> )
> ],
> ),
> ),
> );
> });
> }),
> );
> }
> }
> 
> you need to figure out some things by yourself like comments and likes after applying this code feeds will be visible at your home page.
> 
> AND THAT'S IT HOPE THIS WORK FOR YOU !!

thanks. i fixed it!. but this app can be built web flutter?

**Comment by mdanics** [comment] 2020-10-13 14:03
Closing because the issue is solved. 

At the moment this project is not compatible with Flutter Web

**Closed as completed** 2020-10-13 14:02 UTC
