### ISSUE TITLE
NoSuchMethodError: The getter 'photoUrl' was called on null.

### ISSUE THREAD

**Issue by 0x13ens** [mdanics/fluttergram#6] opened 2018-06-20 07:40 UTC
Getting this error on when new accounts try to use the camara to take a photo?

`NoSuchMethodError: The getter 'photoUrl' was called on null.
Receiver: null
Tried calling: photoUrl`

Any ideas?

**Comment by mdanics** [comment] 2018-06-22 03:12
When does this happen?  When they try to post the photo? When they click the capture button in the camera view?

**Comment by mdanics** [comment] 2018-06-27 02:49
Closing for lack of response and unable to reproduce

**Comment by michaelchow2324** [comment] 2019-02-07 16:17
I got this error too when I tried to add a photo from a library, any ideas to solve this issue?

**Comment by GustavoContreiras** [comment] 2019-03-31 22:18
I got it too. Restarted app and it was solved.

Edit: It happened when I forgot to change the url on feed.dart file. I'm gonna try to reproduce again.

**Comment by mdanics** [comment] 2019-03-31 22:27
@michealchow2324 @GustavoContreiras are you guys able to reproduce this error?

**Comment by GustavoContreiras** [comment] 2019-03-31 22:42
- Deleted user authentication on firebase console
- Deleted user posts on database
- Logged in with user
- Set username
- Went to upload photo page
- Took a photo
- Clicked on confirmation
![image](https://user-images.githubusercontent.com/38460351/55296230-e9b74480-53ec-11e9-96db-ec733e1615b7.png)
First try debug console: https://pastebin.com/qKAZBZmQ

- Closed app
- Restarted
- Went to upload photo page
- Took a photo
- Clicked on confirmation
![image](https://user-images.githubusercontent.com/38460351/55296272-69ddaa00-53ed-11e9-9910-d9242634e7da.png)
Second try debug console: https://pastebin.com/whiiviH9

**Comment by mdanics** [comment] 2019-05-03 05:47
This is now fixed with the improvements with the username screen.
The issue was that `currentUserModel` was not correctly being assigned during the sign up and username selection process.

**Closed as completed by mdanics** 2019-05-03 05:47 UTC
